# Generated by Django 2.2.1 on 2019-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
